"use client";
import { useCallback, useState, type ReactNode } from "react";
import { Button, EmptyState, ErrorBanner, Sheet, Skeleton, Toast } from "@/components/ui/primitives";
import { ModeBadge, type Mode } from "./shell";
import { ActionCard, BillLine, BillSummary, ChatBubble, EventLogItem, InsightCard, InputModeTabs, KhataRow, MoneyText, PaidToast, PaymentStatus, StockDelta, VoiceComposer, type ActionState, type InputMode, type PaymentState, type VoiceState } from "./components";
import { previewFixture as fixture } from "@/lib/ui-fixtures";

function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="guide-section"><h2 className="section-label">{title}</h2>{children}</section>; }
export function Styleguide() {
  const [mode, setMode] = useState<InputMode>("Parchi");
  const [action, setAction] = useState<ActionState>("pending");
  const [voice, setVoice] = useState<VoiceState>("idle");
  const [text, setText] = useState("");
  const [sheet, setSheet] = useState(false);
  const [toast, setToast] = useState(false);
  const dismiss = useCallback(() => setToast(false), []);
  return <><p className="section-label mb-2">Development only</p><h1>Component styleguide</h1><p className="secondary mt-3">Visual fixtures, not business activity. Amounts and quantities are unavailable until seed data exists. All interactions stay on this page.</p>
    <Section title="Typography & surfaces"><div className="card space-y-3"><p className="display-amount">Amounts in INR</p><p className="text-[22px] font-bold leading-7">Screen title</p><p className="section-label">Section label</p><p>Body · Geist</p><p lang="hi">नमस्ते, अपनी दुकान का हिसाब देखिए।</p><p className="secondary">Secondary text</p><p className="caption text-muted">Caption and source</p></div><div className="grid grid-cols-2 gap-2">{[{ name: "Navy", cls: "bg-navy-950 text-surface" }, { name: "Primary blue", cls: "bg-blue-600 text-surface" }, { name: "Sky accent", cls: "bg-sky-500 text-navy-950" }, { name: "Surface", cls: "bg-surface text-ink" }, { name: "Success", cls: "tone-success" }, { name: "Warning", cls: "tone-warning" }, { name: "Danger", cls: "tone-danger" }, { name: "Canvas", cls: "tone-neutral" }].map(s => <div key={s.name} className={`rounded-sm border border-line p-4 text-sm ${s.cls}`}>{s.name}</div>)}</div></Section>
    <Section title="Buttons, input, sheet & toast"><div className="flex flex-wrap gap-2"><Button onClick={() => setSheet(true)}>Open sheet</Button><Button variant="secondary" onClick={() => setToast(true)}>Preview toast</Button><Button variant="quiet" onClick={() => setToast(true)}>Quiet action</Button><Button disabled>Unavailable</Button></div><label className="grid gap-2 text-sm">Text input<input className="field" placeholder="Type here" /></label><Sheet open={sheet} onClose={() => setSheet(false)} title="Preview sheet"><p>This sheet is keyboard accessible. Escape closes it and returns focus to its trigger.</p><Button className="mt-4 w-full" onClick={() => setSheet(false)}>Done</Button></Sheet>{toast && <Toast message="Preview only · no action sent" onDismiss={dismiss} />}</Section>
    <Section title="ModeBadge · all modes"><div className="flex flex-wrap gap-2">{(["demo", "staging", "mock", "live-off"] as Mode[]).map(m => <ModeBadge key={m} mode={m} />)}</div></Section>
    <Section title="MoneyText · sizes & tones"><p className="caption text-muted">Unavailable is a dash, never a zero balance.</p><div className="card flex items-center justify-between">{(["sm", "md", "display"] as const).map(size => <MoneyText key={size} paise={fixture.amountPaise} size={size} />)}</div><div className="flex justify-between"><MoneyText paise={fixture.amountPaise} tone="success" /><MoneyText paise={fixture.amountPaise} tone="danger" /><MoneyText paise={fixture.amountPaise} strike /></div></Section>
    <Section title="InputModeTabs · selected & unselected"><InputModeTabs value={mode} onChange={setMode} /><p role="status" className="caption text-muted">Selected: {mode}</p></Section>
    <Section title="BillLine · confirmed & needs check"><BillLine line={{ name: fixture.product, qty: fixture.quantity, pricePaise: fixture.amountPaise, state: "confirmed" }} /><BillLine line={{ name: "Biscuit — which one?", qty: fixture.quantity, pricePaise: fixture.amountPaise, state: "needs-check", reason: "Parchi text needs confirmation", candidates: fixture.candidates.map((c) => ({ id: c, label: c })) }} onChoose={() => setToast(true)} /><p className="caption text-muted">Quantity controls remain disabled without catalogue quantities.</p></Section>
    <Section title="BillSummary · enabled & blocked"><BillSummary count={null} total={null} onConfirm={() => setToast(true)} /><BillSummary count={null} total={null} disabledReason="Item check karna hai · preview only" /></Section>
    <Section title="PaymentStatus · every state">{(["created", "waiting", "verifying", "paid", "failed", "mock"] as PaymentState[]).map(state => <div key={state}><p className="caption mb-2 text-muted">State preview: {state}</p><PaymentStatus state={state} orderId={null} /></div>)}</Section>
    <Section title="PaidToast · verified appearance"><PaidToast amount={fixture.amountPaise} time={null} preview /><p className="caption text-muted">No verified payment or TTS is triggered by this preview.</p></Section>
    <Section title="StockDelta · normal & low-stock appearance"><StockDelta name={fixture.product} before={null} after={null} reorderLevel={null} /><div className="rounded-sm bg-danger-tint p-3 text-sm text-danger">{fixture.product} · — → — · Low-stock appearance preview</div></Section>
    <Section title="InsightCard & SourceLine"><InsightCard headline="Sales data not available yet" facts={["Connect the sales ledger to see sourced answers."]} source={fixture.source} /><InsightCard headline="Stock insight preview" source={fixture.source} fresh /></Section>
    <Section title="ActionCard · approval & lifecycle"><ActionCard title="Supplier message preview" draft="Namaste, doodh ke stock ke baare mein baat karni hai." state={action} onApprove={() => setAction("approved")} onReject={() => setAction("rejected")} /><Button variant="quiet" onClick={() => setAction("pending")}>Reset preview</Button>{(["approved", "sent", "done", "rejected"] as ActionState[]).map(state => <div key={state}><p className="caption mb-2 text-muted">State preview: {state} · no action sent</p><ActionCard title="Supplier message preview" draft="Draft from the styleguide only." state={state} /></div>)}</Section>
    <Section title="VoiceButton · all states"><div role="group" aria-label="Voice state preview" className="flex flex-wrap gap-2">{(["idle", "listening", "processing", "speaking", "error"] as VoiceState[]).map(state => <Button key={state} variant={state === voice ? "primary" : "quiet"} aria-pressed={voice === state} onClick={() => setVoice(state)}>{state}</Button>)}</div><VoiceComposer value={text} onChange={setText} state={voice} onVoice={() => setVoice(voice === "idle" ? "listening" : "idle")} /><p className="caption text-muted">Animation preview only. The microphone is never accessed.</p><VoiceComposer value="" onChange={() => {}} disabled /></Section>
    <Section title="ChatBubble · Hindi & romanisation"><ChatBubble hindi={fixture.transcript} romanisation={fixture.romanisation} /></Section>
    <Section title="KhataRow · ageing categories">{(["0–15", "16–30", "30+"] as const).map(ageing => <KhataRow key={ageing} name={fixture.customer} ageing={ageing} balance={fixture.amountPaise} />)}<p className="caption text-muted">Age labels demonstrate categories, not actual customer ages or dues.</p></Section>
    <Section title="EventLogItem · normal & verified"><EventLogItem name="action.pending" summary="Draft awaiting approval · appearance preview" timestamp={null} verified={false} /><EventLogItem name="bill.paid" summary="Verified badge appearance · no payment occurred" timestamp={null} verified /></Section>
    <Section title="Empty, loading & error"><EmptyState title="Data not connected" description="Records will appear here when the database is ready." /><Skeleton /><ErrorBanner message="Load nahi hua. Phir se try karein." onRetry={() => setToast(true)} /></Section>
  </>;
}
